-- AlterTable
ALTER TABLE "CourtSetting" ADD COLUMN     "endMin" INTEGER NOT NULL DEFAULT 1260,
ADD COLUMN     "slotMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "startMin" INTEGER NOT NULL DEFAULT 540;
